DROP TABLE APPS.XXCCT_GL_COMBINATIONS_CON CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXCCT_GL_COMBINATIONS_CON
(
  ACTIVADO                   VARCHAR2(1 BYTE),
  PRESERVADO                 VARCHAR2(1 BYTE),
  CUENTA                     VARCHAR2(155 BYTE),
  TIPO                       VARCHAR2(240 BYTE),
  FECHA_DESDE                DATE,
  FECHA_HASTA                DATE,
  AUTORIZAR_CONTABILIZACION  VARCHAR2(1 BYTE),
  AUTORIZAR_PRESUPUESTO      VARCHAR2(1 BYTE),
  CUENTA_ALTERNA             NUMBER(15),
  CONCILIAR                  VARCHAR2(1 BYTE),
  CREATED_BY                 NUMBER,
  REQUEST_ID                 NUMBER,
  LAST_UPDATE_DATE           VARCHAR2(17 BYTE),
  LAST_UPDATED_BY            NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON APPS.XXCCT_GL_COMBINATIONS_CON TO BOLINF;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON APPS.XXCCT_GL_COMBINATIONS_CON TO XXCCS;
